/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef APP_H
#define APP_H

#include <string>

//name spaces for methods
namespace BachelorCpp {
    class instFile {
        public:
        int rdFl(std::string path);
    };
}

#endif
