/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "app.h"
#include <cassert>
#include "adjacencyList.h"
#include <iostream>

void testFileIntoAdjLst(){
    BachelorCpp::createAdjList listMaker;
    vector<vector<pair<int, double>>> adjlst{};
    assert(listMaker.createList("C:/Users/aske-/CLionProjects/BachelorCpp/app/src/resources/adjlist", "file", adjlst) == 0);
    //assert(listMaker.createList("C:/Users/aske-/CLionProjects/BachelorCpp/app/src/resources/denmark", "file") == 0);

}

void testAdjListImplementation(){
    BachelorCpp::createAdjList listMaker;
    vector<vector<pair<int, double>>> adjlst{};
    assert(listMaker.createList("C:/Users/aske-/CLionProjects/BachelorCpp/app/src/resources/adjlistWLongs", "file", adjlst) == 0);
    adjacencyList test;
    test.printGraph(adjlst);

}


//test methods
int main() {
    //BachelorCpp::createAdjList adjListTester;
    //adjListTester.dummyVector();
    //testFileIntoAdjLst();

    testAdjListImplementation();

    return 0;
}






