/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "app.h"
#include <cassert>
#include <iostream>

//test methods
int main() {
    BachelorCpp::createAdjList listMaker;
    //assert(listMaker.createList("C:/Users/abg/CLionProjects/BachelorCpp/app/src/main/cpp/adjlist", "file") == 0);
    assert(listMaker.createList("C:/Users/abg/CLionProjects/BachelorCpp/app/src/main/cpp/denmark", "file") == 0);
    return 0;

}
