/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "app.h"

std::string BachelorCpp::Greeter::greeting() {
    return std::string("Hello, World!");
}
//DO THE STUFF
int main () {
    BachelorCpp::Greeter greeter;
    std::cout << greeter.greeting() << std::endl;
    return 0;
}
