/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <stdlib.h>
#include "app.h"
#include <adjacencyList.h>
#include <iostream>
#include <fstream>
#include <string>
#include <utility>
#include <FileReader.h>

using namespace std;
//DO THE STUFF
int main () {
    return 0;
}


int BachelorCpp::createAdjList::createList(std::string path, std::string method) {
    //vector<pair<int, int>> adjlst[];
    //adjacencyList test;
    //test.addEdge(adjlst,1,2,15);
    //test.printGraph(adjlst,1);
    if(method == "file"){
        FileReader reader;
        reader.readFile(std::move(path), "adjlst");
    }
    return 0;
}
